@echo off
echo Fixing Wrangler version mismatch...
echo.
echo Step 1: Removing node_modules...
rmdir /s /q node_modules
echo.
echo Step 2: Removing package-lock.json...
del package-lock.json
echo.
echo Step 3: Installing fresh dependencies (this may take a minute)...
npm install
echo.
echo Step 4: Starting wrangler...
npm run dev
